# Generated by Django 4.2.7 on 2023-12-24 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=254, verbose_name='Email form')),
                ('subject', models.CharField(max_length=80, verbose_name='Subject')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('name', models.CharField(default='Unknown', max_length=64, verbose_name='Name')),
                ('body', models.CharField(blank=True, max_length=2048, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=64, verbose_name='Path')),
                ('request_method', models.CharField(max_length=10, verbose_name='Request Method')),
                ('time', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'RequestResponseLog',
                'verbose_name_plural': 'RequestResponseLogs',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=255, verbose_name='Source URL')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Buy')),
                ('sell', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sell')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('currency_type', models.SmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro'), (3, 'Hryvnia')], default=3, verbose_name='Currency type')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.source')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
    ]
