# Generated by Django 4.2.7 on 2023-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_source_alter_rate_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('UAH', 'Hryvnia')], max_length=3),
        ),
    ]
