# Generated by Django 4.2.7 on 2023-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.SmallIntegerField(choices=[(1, 'Dollar'), (2, 'Euro'), (3, 'Hryvnia')], default=3),
        ),
    ]
