# Generated by Django 4.2.7 on 2023-12-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_requestresponselog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestresponselog',
            options={'verbose_name': 'RequestResponseLog', 'verbose_name_plural': 'RequestResponseLogs'},
        ),
        migrations.AlterField(
            model_name='requestresponselog',
            name='time',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Time'),
        ),
    ]
